name: flutter_gps_app
description: Пример Flutter-приложения
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Добавите gps позже, когда понадобится

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true